name: Docker Image CI

on:
  push:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag layercraft/connector:$VERSION --build-arg TOKEN=$TOKEN --build-arg USERNAME=$USERNAME
        env:
          USERNAME: ${{ github.repository_owner }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker image
        run: docker push ghcr.io/layercraft/connector:$VERSION
