name: Docker Image CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag app --build-arg TOKEN=$TOKEN --build-arg USERNAME=$USERNAME
        env:
          USERNAME: ${{ github.repository_owner }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Tag rename to ghcr.io
        run: docker tag app ghcr.io/layercraft/connector:$VERSION && docker tag app ghcr.io/layercraft/connector:dev-latest

      - name: Push the Docker image to GitHub Container Registry
        run: docker push ghcr.io/layercraft/connector:$VERSION && docker push ghcr.io/layercraft/connector:dev-latest
