name: Gradle Build

on:
  push:
  pull_request:

jobs:
  distribution:
    name: Build Distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'gradle'

      - name: Build Gradle distribution
        run: ./gradlew assembleDist
        env:
          USERNAME: ${{ github.repository_owner }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Gradle distribution
        uses: actions/upload-artifact@v3
        with:
          name: Distribution
          path: | 
            build/distributions/*.zip
            build/distributions/*.tar

  jar:
    name: Build Jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build
        env:
          USERNAME: ${{ github.repository_owner }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Jar
        uses: actions/upload-artifact@v2
        with:
          name: Connector.jar
          path: build/libs/*.jar
